### ISSUE TITLE
Build is broken by pgf bug

### ISSUE THREAD

**Issue by paolobrasolin** [paolobrasolin/kodi#19]
Versions `3.1` and `3.1.1` of `pgf` have a bug which makes them incompatible with engines missing `etex` extensions. Specifically, `\scantokens`.

More informations here: https://tex.stackexchange.com/q/473365/82186

The bug (known) was introduced by [ac33f7](https://sourceforge.net/p/pgf/git/ci/ac33f7/) while fixing [#306](https://sourceforge.net/p/pgf/bugs/306/).
It was solved by [287814](https://sourceforge.net/p/pgf/git/ci/287814/), [46eaad](https://sourceforge.net/p/pgf/git/ci/46eaad/), and [4abefd](https://sourceforge.net/p/pgf/git/ci/4abefd/) thus closing [#508](https://sourceforge.net/p/pgf/bugs/508/).

The solution amounts to a generalization of [this old shim](https://sourceforge.net/p/pgf/git/ci/55cc7b/tree/tex/generic/pgf/frontendlayer/tikz/libraries/tikzexternalshared.code.tex#l1419). The shim essentially is
```tex
\long\def\scantokens#1{#1}
```

### TODO

- [x] temporarily patch the build with the shim
- [ ] ~~remove the shim from the build framework once `pgf > 3.1.1`is released~~
- [ ] ~~add note in the documentation about using the shim before `\input`ing `kodi` if no `etex` extensions are available~~
- [x] remove the shim from the build framework and abandon `tex` in favour of `etex`
- [ ] add note in the documentation about `etex`

**Comment by paolobrasolin** [comment]
Henri decided do make `eTeX` a hard requirement with https://github.com/pgf-tikz/pgf/commit/187f5f484720100c9cfab49aa90832c2b2fcc6c1

I definitely can't blame him.
